### ISSUE TITLE
Create the generator

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs-heroku#2]
This issue is to build this generator. When running like:

```
donejs add heroku
```

Should ask if you have already created an app. By default, if no answer is given, it will create a new app after logging in.

```
donejs add heroku <app-name>
```

Will login and select `<app-name>` as the app to operate on. The process should be, roughly:

1. Install the heroku toolbelt. (__Note__: that this might not be possible to do for the user. Ideally we could. If not possible then we should check if it is installed and if not give the user some instructions on how to do that.)
2. Login, if not already so.
3. Configure heroku to use `<app-name>`.
4. Add a procfile.
5. Instruct the user to use `git push heroku master` to deploy the first time. (__Note__: Should we go ahead and do this when the generator is added? I lean towards no, because the user might already have an existing app and don't want to override it.)

**Comment by m-mujica** [comment]
>1. Install the heroku toolbelt. (Note: that this might not be possible to do for the user. Ideally we could. If not possible then we should check if it is installed and if not give the user some instructions on how to do that.)

The CLI is available as a node package, although heroku recommends not to use it for several reasons, since using their recommended installation method require us to deal with OS-level stuff, I guess we could install the npm package (if heroku is not an available command) and show the same warning they use on their docs

https://devcenter.heroku.com/articles/heroku-cli#npm

> It’s strongly recommended to use one of the other installation methods if possible This installation method will not autoupdate and requires you to use the system node which may be older than the node we develop for. We tend to use very current releases of node and do not back-support older versions. If you use any of the other methods of install, it will include node and won’t conflict with any node on the system.

**Comment by m-mujica** [comment]
> 2. Login, if not already so.

Wondering how can we make our generator wait until the user is logged in, meaning, we'll run `heroku login` from the generator, but not sure if there is a way to wait until the user finished the process so the generator can continue its thing.

**Comment by matthewp** [comment]
Let's not worry about installing heroku. We can leave that instruction in the guide for now.

I think if we launch `heroku login` as a subprocess it will stay open until the user finishes the process. So I think waiting on the exit code will suffice.
